defaults:
  - experiment: minimal
  - training: ppo_test
  - model: gnn
  - obs_space: graph
  - reward: constant
  - env: case14
  - opponent: disabled
  - evaluation: minimal
  - rollouts: minimal
  - callbacks: default
  - optimization: disabled
  - _self_

hydra:
  job:
    chdir: false
  run:
    dir: ${experiment.storage_path}/${experiment.name}
